### PR TITLE
fix: thorvg canvas resize problem.

### PR DESCRIPTION
**Pull request by hermet**
The canvas syncs before changing a target buffer.

https://github.com/thorvg/thorvg/issues/2580

### CODE REVIEW

**Comment by theashraf** [comment]
@hermet the resize issue is not fixed yet. please check this recording for thorvg 0.14.x. calling resize causes a rendering issue:

https://github.com/user-attachments/assets/885b9ab5-4cc8-431a-a1ae-acfd861c7f27

but thorvg 0.13.x still renders properly after calling resize:

https://github.com/user-attachments/assets/9ca8b51e-8776-436d-b5a8-cb931c51d422

**Comment by hermet** [comment]
@theashraf Hi, It looks like the target size is not correctly set in width/height. May I ask you to check the return value of both `tvg_swcanvas_set_target()` and `tvg_canvas_sync()` in the problematic `resize()`?

**Comment by theashraf** [comment]
@hermet  only tvg_canvas_sync returns TVG_RESULT_INSUFFICIENT_CONDITION (2), while tvg_swcanvas_set_target returns TVG_RESULT_SUCCESS (0).

**Comment by hermet** [comment]
@theashraf Hmm. tvg_swcanvas_set_target() seems working then. 

Upon examining the video, it appears that the actual buffer size is larger than the width and height specified by ThorVG. If the reverse were true, it would cause crashes rather than displaying a broken image. It's possible that dotLottie is passing the wrong width and height, which differs from the actual target buffer. Is this a possibility?

One more question:  It also resized smaller properly when the panel size is narrowed. How's different when the resize button is clicked?

**Comment by hermet** [comment]
@theashraf Just in case, could you please double-check that the buffer, width, and height values are properly updated when `resize()` is called? It's suspicious that it still holds the previous larger buffer and uses it in the web canvas.

**Comment by samuelOsborne** [comment]
@theashraf I've updated to the most recent release of thorvg( v0.14.5) in this PR: 

https://github.com/LottieFiles/dotlottie-rs/pull/216

As well as added @hermet's changes and can't reproduce the bug, could you please check on your end ? You can find the artifacts for that branch already built here:

https://github.com/LottieFiles/dotlottie-rs/actions/runs/10332417019

**Review by theashraf — APPROVED** [review]

**Comment by hermet** [comment]
@samuelOsborne @theashraf fixed?

**Comment by theashraf** [comment]
> @samuelOsborne @theashraf fixed?

@hermet Yes, fixed with your changes + upgrading ThorVG to v0.14.5

**Comment by theashraf** [comment]
@hermet The issue with dotlottie-rs still persists, even after applying the suggested fix.

I've verified that the frame buffer is being resized correctly and matches the canvas width and height. Below is the relevant code on web. The resize function appears to be working as expected, and the frame buffer size is updated accordingly based on the new canvas dimensions.

```js
function resize() {
  const { width: clientWidth, height: clientHeight } = canvas.getBoundingClientRect();

  const width = Math.floor(clientWidth * (window.devicePixelRatio || 1));
  const height = Math.floor(clientHeight * (window.devicePixelRatio || 1));

  canvas.width = width;
  canvas.height = height;

  dotLottiePlayer.resize(width, height);
}

function render() {
  const rendered = dotLottiePlayer.render();
  if (rendered) {
    const actualFrameBuffer = dotLottiePlayer.buffer();
    const expectedFrameBufferSize = canvas.width * canvas.height * 4;

    if (actualFrameBuffer.length !== expectedFrameBufferSize) {
      // never fails 🤔 
      throw new Error("Frame buffer size mismatch");
    }

    const imageData = ctx.createImageData(canvas.width, canvas.height);
    imageData.data.set(actualFrameBuffer);
    ctx.putImageData(imageData, 0, 0);
  }
}
```

Despite the frame buffer resizing as expected, the problem persists. Could you provide any further insights into what might be causing this ?

**Comment by hermet** [comment]
I think it needs a user-side update, as thorvg.viewer has no regressions so far
\+ Could you please review the dotlottie? @tinyjin 

https://github.com/user-attachments/assets/509d03cc-210c-4bc5-b801-9f9a68dde306

**Comment by tinyjin** [comment]
@theashraf Hello, I'm on checking this issue. Have just installed dotlottie-web and run web-example. Although I trigger `resize`, the issue doesn't appear.

How can I reproduce same situation you're encountering?

https://github.com/user-attachments/assets/e2f0094d-4df0-4047-b2b4-d2f1fd567521

**Comment by samuelOsborne** [comment]
@tinyjin Please try resize the canvas by modifying its width / height in the inspector, then clicking resize

**Pull request merged**
